### ISSUE TITLE
[Others] 확성기 디자인 변경

### ISSUE THREAD

**Issue by Clearsu** [42organization/42gg.client#1143]
## Desc

- 현 확성기 디자인이 전체적인 테마와 통일감이 부족하다고 생각되어 디자인을 수정하고자 합니다.

## Detail
현 디자인과 변경 시안 중 더 마음에 드시는 항목에 코멘트로 투표 부탁드립니다.
배너 배경의 투명도를 높여 뒷 배경의 보라색이 투과되도록 하고, 시인성을 위해 테두리를 추가하였습니다.

1. 현 디자인 유지
<img width="343" alt="image" src="https://github.com/42organization/42gg.client/assets/67998022/935a9150-b220-4bd3-af3d-2c6086e4277c">

2. 변경 디자인 - 테두리 없음
<img width="339" alt="image" src="https://github.com/42organization/42gg.client/assets/67998022/65e07f5b-c60d-4e5b-8877-e1d03aa587bf">

3. 변경 디자인 - 테두리 있음
<img width="341" alt="image" src="https://github.com/42organization/42gg.client/assets/67998022/429a28f5-818c-490b-a43f-7b4058404f15">

**Comment by yoouyeon** [comment]
저는 "1번 현 디자인 유지" 나 "2번 테두리 없음"에 투표하고 싶습니다.
메인 페이지 컴포넌트들에 대부분 테두리가 없다 보니 3번처럼 테두리를 넣게 되면 개인적으로는 좀 통일감이 떨어져보이는 느낌이예요.

**Comment by PHJoon** [comment]
저는 2번 투표합니다. 다만 rgba 알파값을 좀 더 높여서 2번 캡쳐본보다 살짝 더 진한 색상이면 좋을 것 같습니다.

**Comment by Clearsu** [comment]
@yoouyeon @PHJoon @hyobb109 의견 감사합니다 :)
