### ISSUE TITLE
[Feat] 지원자페이지 구현

### ISSUE THREAD

**Issue by parksangmin1543** [42organization/42gg.client#1254]
### Description

지원자페이지 구현

### Todo

- [ ] 지원자 입력 구현
- [ ] 테이블 데보기 구현
- [ ] 스크롤바 구현

**Comment by nerdchanii** [comment]
#1337 에서 머지된것으로 확인되는 기능이라 이슈를 닫습니다. 필요시 다시 열어주세요.
