### ISSUE TITLE
[Bug] 로그인 보상을 수령해도, 계속 화면이 뜨는 이슈

### ISSUE THREAD

**Issue by joonho0410** [42organization/42gg.client#1525]
## Reproduce

1.  로그인 보상을 수령후 다른 페이지로 이동했다가, 다시 돌아오는 경우. 로그인 보상화면이 다시 있음
2.  
3.  

## Wanted

로그인 보상 수령후, 메인페이지에 다시 돌아와도 해당 화면이 뜨지 않는것

**Comment by nerdchanii** [comment]
@joonho0410 #1528에서 머지 된 것으로 보여 이슈를 닫습니다. 필요시 다시 열어주세요.
