### ISSUE TITLE
[Bug] agenda admin 버그

### ISSUE THREAD

**Issue by irenee-14** [42organization/42gg.client#1531]
## Desc

agenda admin 버그

## Reproduce

1. 모달에서 아젠다를 선택하려고 할 경우 모달 뒤에 select 목록이 표시됨
2. admin 공지사항 없을 때 조회할 경우 에러 뜸
3. 대회 상세정보에서 포스터가 이미 존재하는지 알 수 없음

## Wanted

- [x] 모달에서 아젠다를 정상적으로 선택 가능
- [x] 공지사항이 존재하지 않을 경우에도 에러가 뜨지 않도록 변경
- [x] 대회 상세정보에서 포스터 조회
- [x] 정보가 없을 경우에 pagenation 뜨지 않도록 위치 변경

**Comment by nerdchanii** [comment]
@irenee-14 #1537에서 머지된 것으로 확인되어 이슈를 닫습니다. 필요시 다시 열어주세요.
