### ISSUE TITLE
[Bug] 아젠다 전반적 버그 및 수정사항 반영

### ISSUE THREAD

**Issue by irenee-14** [42organization/42gg.client#1551]
## Desc

1. 프로필 기본 문구 수정 안됨
2. 호스트페이지 버튼 제대로 동작하는지
3. 진행완료 아젠다 있는데 agenda page의 진행완료 페이지에는 나타나지 않는다..?
4. 조건 탭 빼서 상세정보에 넣기

## Reproduce

1.  
2.  
3.

**Comment by nerdchanii** [comment]
#1563 PR에서 해당 이슈가 해결된 것으로 보여 close합니다. 이슈가 끝나지 않았다고 판단되시면 다시 열어주세요.
