### ISSUE TITLE
[Bug] 모바일 UI 깨짐

### ISSUE THREAD

**Issue by cweedlee** [42organization/42gg.client#1554]
## Desc

모바일 UI 깨짐, 아이폰 파란글씨 이슈 남아있는 문제 해결 필요

## Reproduce

1.  
2.  
3.

**Comment by nerdchanii** [comment]
@cweedlee #1556 에서 해당이슈가 머지된 걸 확인해서 이슈를 닫습니다. 필요시 다시 열어주세요.
