### ISSUE TITLE
[Refactor] 가시성 개선 및 css 버그 수정

### ISSUE THREAD

**Issue by irenee-14** [42organization/42gg.client#1572]
## Desc

가시성 개선 및 css 버그 수정

## Wanted

- [x] 대회 종료api url 변경

- [x] 인덱스 페이지에서 클릭 이벤트 확인
- [x] 프로필 가기 가시성 개선

- 기존 gg와의 통일성 
  - [x] 햄버거바 위치 조정
  - [x] index페이지 및 agenda페이지에 햄버거 바에 지원하기 추가
  - [x] 지원하기 페이지 css 수정

**Comment by nerdchanii** [comment]
@irenee-14 #1573에서 작업이 완료된 것으로 확인되어 이슈를 닫겠습니다. 아직 끝나지 않은 이슈라고 생각하시면 다시 열어주세요.
