### ISSUE TITLE
[Bug] 카카오 로그인 기능 오류

### ISSUE THREAD

**Issue by yoouyeon** [42organization/42gg.client#1580]
## Desc

카카오 로그인이 되지 않습니다.

## Reproduce

1. 42 계정과 연동되지 않은 카카오 계정 준비
2. 기존 로그인 계정 로그아웃
3. 카카오 로그인 버튼 클릭
4. 카카오 로그인 프로세스 진행
5. 404 페이지로 리다이렉트 됨
6. 다시 로그인 페이지로 리다이렉트 됨

## Wanted

카카오 로그인 후에도 gg 서비스를 제한적으로 이용할 수 있어야 합니다.

## Bug img / video

(이미 카카오 로그인이 되어 있는 상태라 4번째 로그인 프로세스는 생략되어있습니다.)

https://github.com/user-attachments/assets/1757a34c-a401-4db0-9df8-fec020c43cc9

## Etc

이 버그가 언제부터 있었는지 알 수 없어서
로그인 이후에 내부 서비스들에서 42 계정과 연동되지 않은 카카오 유저의 권한 처리도 같이 점검해 보는 것이 좋을 것 같습니다.

**Comment by AreSain** [comment]
백엔드 이슈로 판명되어 수정하겠습니다. 이 이슈는 미리 닫고, [https://github.com/42organization/42gg.server.dev.v2/issues/1075](url) 에서  처리하겠습니다.
