### ISSUE TITLE
[Feat]  GA4 적용하기

### ISSUE THREAD

**Issue by pearpearB** [42organization/42gg.client#206]
### ISSUE
 * Type: `feature`
 * Detail: google analytics 4 적용하기

**Comment by mike2ox** [comment]
## 참고 이슈
- #337

**Comment by mike2ox** [comment]
## 결론
- 현재 GA 데이터가 쌓이고는 있으나 데이터가 세분화되있지 않아 새로 설정이 필요(구글 태그 매니저 설정 필요한 것으로 보임)
- But, GA보다 의미있는 통계 데이터를 보여주는게 현 시점에서 더 의미가 있다고 판단
- GA는 신규 서비스를 오픈하게 되거나(상점 / 인벤토리 / 재화 시스템, 추천 시스템 등) 외부유저도 유입이 될 경우에 업데이트하기로 결정
