### ISSUE TITLE
[Feat]  어드민 페이지 만들기

### ISSUE THREAD

**Issue by pearpearB** [42organization/42gg.client#337]
### ISSUE
 * Type: `feature`
 * Detail: 어드민 페이지 만들기
 
 ### TODO
- 어드민 페이지 추가
- 기존 어드민 페이지 리팩토링
- 데이터 분석용 그래프 추가하기(=> 통계)
  - [x] (SimpleLineChart) 일일 접속자 수 - 하루에 42gg를 이용하는 총 이용자 수를 알 수 있다.(메인 페이지 접속자 수) (일별/주별/월별)
  - [x] (SimpleLineChart) 일일 매치 이용자 수 - 매치 **성사된** 사람의 숫자가 얼마나 되는지 (일별/주별/월별) / 중복 유저 포함
  - [x] (LineBarAreaComposedChart) 주별 매치 이용자 수 (성사된 매치 수 * 2 / 매칭을 한 유니크한 유저) - 매치가 많이 되었어도 특정 유저들만 사용한 것을 확인해볼 수 있다. / 중복 유저 제외
  - [x] (BiaxialLineChart) 일일 접속자 수 대비 일일 매치 이용자 수 - 접속자가 많은 날 매치가 많이 일어나는 지 알 수 있다.
  - [x] (BiaxialBarChart) 시간별 슬롯 이용률 - 시간대별 이벤트 도입할수 있다. (주별/월별)
  - [x] (PieChartWithCustomizedLabel) 슬롯을 언제 등록하는지 시간 - 얼리버드 도입 가능성(슬롯 시간 기준으로 몇분 전에 등록하는지/ x:매칭횟수 y: 0-5분,5-10분,10-30분,1-2시간, 그 이상)
  - [x] 매칭 취소 횟수 & 유저리스트 (2개, canceledByTime/canceledByMan) - canceledByTime이 많은 경우는 ppp차이가 많이 나기 때문에 매치 방식을 수정시켜줘야 할 수도, 중복된 유저가 canceledByMan일 경우 모니터링 필요 (일별/주별/월별)
  - [x] 랭크별 일일 접속자 수 : 점수로 나누지 말고 **등수**로 구간을 나눠 보여줌
  - [x] 랭크별 일일 매치 이용자 수
  - [x] (PieChartWithCustomizedLabel) 기수별 매칭 이용자 수 → 랭크가 있는 이용자 중 기수 비율
  - [ ] (?) 이벤트 시기에 이용자 수 변화(일일 이용자 수에 이벤트 시작 날 점으로)
  - [ ] (new) 헤비유저 행동분석

일단 만들고 추가해보도록 합시다

**Comment by tamagoyakii** [comment]
기수별 매칭 이용자 수는 서비스 업데이트에 필요하지 않다고 판단하여 그래프 목록에서 제거하지 않았었나요??

**Comment by pearpearB** [comment]
어제 회의에서 다시 필요하단 이야기가 나왔습니당! 앞으로 업데이트 시기에 대해서도 생각해볼 수 있을 거란 의견이 나와서요
