### ISSUE TITLE
[Document] 업데이트 목록 정리

### ISSUE THREAD

**Issue by tamagoyakii** [42organization/42gg.client#598]
### ISSUE
 * Type: `feature`
 * Detail: 1기에서 마치지 못한 task 들을 정리했습니다. 
 
 ### TODO
- **점수 입력 방법 수정**
: 쌍방의 동의가 있을 때 점수가 확정되도록 수정해야 합니다.
- **`seasonMode(rank/normal/both)`에 따른 에러 처리**
: 현재 `both` 모드로 사이트가 운영되고 있습니다. 일반전 업데이트 이전 `rank` 모드로 운영되었기 때문에 `both/rank`모드는 큰 문제가 없을 것이라고 생각됩니다. 하지만 `normal` 모드로의 운영을 해본 적이 없기 때문에, 해당 모드일 때의 에러 확인이 필요합니다.
- **Admin Page 업데이트**
: 현재의 관리자 페이지는 백엔드에서 구현한 페이지입니다. 저희에게 정말 필요한 기능들을 넣은 관리자 페이지를 새롭게 만들고 싶습니다.
- **통계 페이지 구현**
- **매칭 버튼(탁구채 버튼)이 매칭 버튼 수정**
: 처음 사이트에 접속했을 때 탁구채 버튼이 매칭 버튼인지 모르겠다는 의견이 많았습니다. 해당 버튼을 업데이트할 필요가 있을 것 같습니다.
- **`-webkit-fill-available` 적용 및 헤더 고정**
: height가 100vh로 고정되어 있어 모바일 크롬/사파리로 사이트에 접속할 경우 페이지가 실제로 보이는 뷰보다 길게 나타납니다. 때문에 몇몇 모달의 하단부가 보이지 않는 문제들이 있습니다. softwave.42gg.client 레포에 해당 문제를 수정했었으나, 이에 따라 발생하는 다른 문제들 때문에 본 레포로 가져오지 못했습니다.
- **칭호 추가**
: 프로필 페이지나 랭킹 페이지에서 보여질 칭호가 추가됐으면 좋겠습니다.
- #333 
- #585 
- #528

**Comment by mike2ox** [comment]
감사합니다  👍 👍 👍 👍 👍

**Comment by mike2ox** [comment]
## 진행상황
- 3기(23년 2분기 예정) 메인 미션으로 사이트 UI 리뉴얼을 검토중이라 기존 디자인에 종속된 todo는 후순위 or issue 발급을 하지 않았습니다. (기존에 만들어진 것은 예외)
