### ISSUE TITLE
[Feat] 관리자 피드백 모달 개선

### ISSUE THREAD

**Issue by 42sungwook** [42organization/42gg.client#651]
## Desc
피드백 모달 CSS 기능 및 CSS 개선
## Detail
보내기 아이콘 추가 및 UI 개선
## Todo
- [x] 전체적인 색 변경
- [x] 버튼 스타일 변경

**Comment by mike2ox** [comment]
## 현재 상황
- 기존 서비스 스타일 레이아웃 위에 스타일을 입히고 있어서 걷어내는 작업이 필요
