### ISSUE TITLE
[Bug] 메인에서 이모지를 

### ISSUE THREAD

**Issue by raehy19** [42organization/42gg.client#658]
## Desc

메인에서 상태 메시지 글자수로 자를때 이모지가 잘릴 경우 깨짐
이모지가 유니코드라 여러 바이트인데 1 바이트를 기준으로 잘라서 그런것으로 보임

## Wanted

잘리는 부분의 문자가 유니코드인지 확인하는 로직 넣어서 이모지 깨짐 해결

## Bug img / video

<img width="467" alt="image" src="https://user-images.githubusercontent.com/69339099/218944160-46bcacec-470b-4b01-9527-9da77f3345de.png">

**Comment by mike2ox** [comment]
## 추가 사항
### Bug img
![image](https://user-images.githubusercontent.com/22931103/226543761-adffad1f-424f-46cc-9a3a-a4e7ed059a5c.png)
![image](https://user-images.githubusercontent.com/22931103/226543806-163e48ec-0349-4f6b-b05c-43dd0b63c314.png)
- 특정 이모지들이 윈도우 크롬에서 제대로 표현이 안되는 것을 확인

### 원인
![image](https://user-images.githubusercontent.com/22931103/226543720-5944d26a-8fbc-4a0c-bb6d-b87ae169927f.png)
- 몇몇 이모지는 사이트 접속하는 브라우저의 버전이나 디바이스 내 해당 이모지가 내장되있지 않아 발생하는 것으로 보임.
- 사용자별 디바이스 내 이모지 버전을 확인할 수 없으므로 버전이 낮은(배포된지 오래된) 이모지들을 사용해야 할 것으로 보임

**Comment by mike2ox** [comment]
UI가 리뉴얼되면서 직접적인 문제 발생이 없어져 close
